/*
 * Generated by XDoclet - Do not edit!
 */
package com.csr.billing.ejb;

/**
 * Home interface for InvoiceEntity.
 */
public interface InvoiceEntityHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/InvoiceEntity";
   public static final String JNDI_NAME="ejb/InvoiceEntity";

   public com.csr.billing.ejb.InvoiceEntity create(com.csr.billing.ejb.InvoiceDTO invoice)
      throws javax.ejb.CreateException,java.rmi.RemoteException;

   public java.util.Collection findAll()
      throws javax.ejb.FinderException,java.rmi.RemoteException;

   public com.csr.billing.ejb.InvoiceEntity findByPrimaryKey(java.lang.Integer pk)
      throws javax.ejb.FinderException,java.rmi.RemoteException;

}
