/*
 * Generated by XDoclet - Do not edit!
 */
package com.csr.billing.ejb;

/**
 * Local interface for InvoiceEntity.
 */
public interface InvoiceEntityLocal
   extends javax.ejb.EJBLocalObject
{

   public java.lang.String getInvoiceNumber(  ) ;

   public java.lang.String getInvoiceDate(  ) ;

   public java.lang.String getTerms(  ) ;

   public java.lang.String getPurpose(  ) ;

   public java.lang.String getPurchaseOrderNum(  ) ;

   public java.lang.Boolean getExempt(  ) ;

   public java.lang.String getDatePrinted(  ) ;

   public void setRownumber( java.lang.String r ) ;

}
