/*
 * Generated by XDoclet - Do not edit!
 */
package com.csr.billing.ejb;

/**
 * CMP layer for InvoiceEntity.
 */
public abstract class InvoiceEntityCMP
   extends com.csr.billing.ejb.InvoiceEntityBean
   implements javax.ejb.EntityBean
{

   public void ejbLoad() 
   {
   }

   public void ejbStore() 
   {
   }

   public void ejbActivate() 
   {
   }

   public void ejbPassivate() 
   {

      InvoiceDTO = null;
   }

   public void setEntityContext(javax.ejb.EntityContext ctx) 
   {
   }

   public void unsetEntityContext() 
   {
   }

   public void ejbRemove() throws javax.ejb.RemoveException
   {

   }

 /* Value Objects BEGIN */

   private com.csr.billing.dto.InvoiceDTO InvoiceDTO = null;

   public com.csr.billing.dto.InvoiceDTO getInvoiceDTO()
   {
      InvoiceDTO = new com.csr.billing.dto.InvoiceDTO();
      try
         {
            InvoiceDTO.setInvoiceNumber( getInvoiceNumber() );
            InvoiceDTO.setInvoiceDate( getInvoiceDate() );
            InvoiceDTO.setTerms( getTerms() );
            InvoiceDTO.setPurpose( getPurpose() );
            InvoiceDTO.setPurchaseOrderNum( getPurchaseOrderNum() );
            InvoiceDTO.setExempt( getExempt() );
            InvoiceDTO.setDatePrinted( getDatePrinted() );

         }
         catch (Exception e)
         {
            throw new javax.ejb.EJBException(e);
         }

	  return InvoiceDTO;
   }

/* Value Objects END */

   public abstract java.lang.String getInvoiceNumber() ;

   public abstract void setInvoiceNumber( java.lang.String invoiceNumber ) ;

   public abstract java.lang.String getInvoiceDate() ;

   public abstract void setInvoiceDate( java.lang.String invoiceDate ) ;

   public abstract java.lang.String getTerms() ;

   public abstract void setTerms( java.lang.String terms ) ;

   public abstract java.lang.String getPurpose() ;

   public abstract void setPurpose( java.lang.String purpose ) ;

   public abstract java.lang.String getPurchaseOrderNum() ;

   public abstract void setPurchaseOrderNum( java.lang.String purchaseOrderNum ) ;

   public abstract java.lang.Boolean getExempt() ;

   public abstract void setExempt( java.lang.Boolean exempt ) ;

   public abstract java.lang.String getDatePrinted() ;

   public abstract void setDatePrinted( java.lang.String datePrinted ) ;

}
