/*
 * Generated by XDoclet - Do not edit!
 */
package com.csr.billing.ejb;

/**
 * Remote interface for InvoiceEntity.
 */
public interface InvoiceEntity
   extends javax.ejb.EJBObject
{

   public java.lang.String getInvoiceNumber(  )
      throws java.rmi.RemoteException;

   public java.lang.String getInvoiceDate(  )
      throws java.rmi.RemoteException;

   public java.lang.String getTerms(  )
      throws java.rmi.RemoteException;

   public java.lang.String getPurpose(  )
      throws java.rmi.RemoteException;

   public java.lang.String getPurchaseOrderNum(  )
      throws java.rmi.RemoteException;

   public java.lang.Boolean getExempt(  )
      throws java.rmi.RemoteException;

   public java.lang.String getDatePrinted(  )
      throws java.rmi.RemoteException;

   public void setRownumber( java.lang.String r )
      throws java.rmi.RemoteException;

}
