/*
 * Generated by XDoclet - Do not edit!
 */
package com.csr.services.client.ejb;

/**
 * Home interface for ClientService.
 */
public interface ClientServiceHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ClientService";
   public static final String JNDI_NAME="ejb/ClientService";

   public com.csr.services.client.ejb.ClientService create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
