/*
 * Generated by XDoclet - Do not edit!
 */
package com.csr.services.client.ejb;

/**
 * Remote interface for ClientService.
 */
public interface ClientService
   extends javax.ejb.EJBObject
{
   /**
    * An example business method
    * @throws EJBException Thrown if method fails due to system-level error.    */
   public void addClient(  )
      throws java.rmi.RemoteException;

   public java.lang.String getClient( int i )
      throws java.rmi.RemoteException;

}
