/*
 * Generated by XDoclet - Do not edit!
 */
package com.csr.clients.ejb;

/**
 * Remote interface for AddressEntity.
 */
public interface AddressEntity
   extends javax.ejb.EJBObject
{

   public java.lang.Integer getAddressID(  )
      throws java.rmi.RemoteException;

   public java.lang.Integer getClientID(  )
      throws java.rmi.RemoteException;

   public java.lang.String getAddress1(  )
      throws java.rmi.RemoteException;

   public java.lang.String getAddress2(  )
      throws java.rmi.RemoteException;

   public java.lang.String getAddress3(  )
      throws java.rmi.RemoteException;

   public java.lang.String getCity(  )
      throws java.rmi.RemoteException;

   public java.lang.String getState(  )
      throws java.rmi.RemoteException;

   public java.lang.String getPostalCode(  )
      throws java.rmi.RemoteException;

   public java.lang.String getCountry(  )
      throws java.rmi.RemoteException;

   public java.lang.String getAddressType(  )
      throws java.rmi.RemoteException;

}
