/*
 * Generated by XDoclet - Do not edit!
 */
package com.csr.clients.ejb;

/**
 * Local interface for AddressEntity.
 */
public interface AddressEntityLocal
   extends javax.ejb.EJBLocalObject
{

   public java.lang.Integer getAddressID(  ) ;

   public java.lang.Integer getClientID(  ) ;

   public java.lang.String getAddress1(  ) ;

   public java.lang.String getAddress2(  ) ;

   public java.lang.String getAddress3(  ) ;

   public java.lang.String getCity(  ) ;

   public java.lang.String getState(  ) ;

   public java.lang.String getPostalCode(  ) ;

   public java.lang.String getCountry(  ) ;

   public java.lang.String getAddressType(  ) ;

}
