/*
 * Generated by XDoclet - Do not edit!
 */
package com.csr.clients.ejb;

/**
 * CMP layer for AddressEntity.
 */
public abstract class AddressEntityCMP
   extends com.csr.clients.ejb.AddressEntityBean
   implements javax.ejb.EntityBean
{

   /**
    * Generated ejbPostCreate for corresponding ejbCreate method.
    *
    * @see #ejbCreate(com.csr.clients.ejb.AddressDTO addressDTO)
    */
   public void ejbPostCreate(com.csr.clients.ejb.AddressDTO addressDTO)
   {
   }

   public void ejbLoad() 
   {
   }

   public void ejbStore() 
   {
   }

   public void ejbActivate() 
   {
   }

   public void ejbPassivate() 
   {

      AddressDTO = null;
   }

   public void setEntityContext(javax.ejb.EntityContext ctx) 
   {
   }

   public void unsetEntityContext() 
   {
   }

   public void ejbRemove() throws javax.ejb.RemoveException
   {

   }

 /* Value Objects BEGIN */

   private com.csr.clients.dto.AddressDTO AddressDTO = null;

   public com.csr.clients.dto.AddressDTO getAddressDTO()
   {
      AddressDTO = new com.csr.clients.dto.AddressDTO();
      try
         {
            AddressDTO.setAddressID( getAddressID() );
            AddressDTO.setClientID( getClientID() );
            AddressDTO.setAddress1( getAddress1() );
            AddressDTO.setAddress2( getAddress2() );
            AddressDTO.setAddress3( getAddress3() );
            AddressDTO.setCity( getCity() );
            AddressDTO.setState( getState() );
            AddressDTO.setPostalCode( getPostalCode() );
            AddressDTO.setCountry( getCountry() );
            AddressDTO.setAddressType( getAddressType() );

         }
         catch (Exception e)
         {
            throw new javax.ejb.EJBException(e);
         }

	  return AddressDTO;
   }

/* Value Objects END */

   public abstract java.lang.Integer getAddressID() ;

   public abstract void setAddressID( java.lang.Integer addressID ) ;

   public abstract java.lang.Integer getClientID() ;

   public abstract void setClientID( java.lang.Integer clientID ) ;

   public abstract java.lang.String getAddress1() ;

   public abstract void setAddress1( java.lang.String address1 ) ;

   public abstract java.lang.String getAddress2() ;

   public abstract void setAddress2( java.lang.String address2 ) ;

   public abstract java.lang.String getAddress3() ;

   public abstract void setAddress3( java.lang.String address3 ) ;

   public abstract java.lang.String getCity() ;

   public abstract void setCity( java.lang.String city ) ;

   public abstract java.lang.String getState() ;

   public abstract void setState( java.lang.String state ) ;

   public abstract java.lang.String getPostalCode() ;

   public abstract void setPostalCode( java.lang.String postalCode ) ;

   public abstract java.lang.String getCountry() ;

   public abstract void setCountry( java.lang.String country ) ;

   public abstract java.lang.String getAddressType() ;

   public abstract void setAddressType( java.lang.String addressType ) ;

}
