/*
 * Generated by XDoclet - Do not edit!
 */
package com.csr.clients.ejb;

/**
 * Local home interface for ClientEntity.
 */
public interface ClientEntityLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ClientEntityLocal";
   public static final String JNDI_NAME="ejb/ClientEntityLocal";

   public com.csr.clients.ejb.ClientEntityLocal create(com.csr.clients.ejb.ClientDTO clientDTO)
      throws javax.ejb.CreateException;

   public com.csr.clients.ejb.ClientEntityLocal create(java.lang.Integer clientID , java.lang.String clientNumber , java.lang.String clientName , java.lang.Double creditLimit , java.lang.Boolean billable)
      throws javax.ejb.CreateException;

   public java.util.Collection findAll()
      throws javax.ejb.FinderException;

   public com.csr.clients.ejb.ClientEntityLocal findByPrimaryKey(java.lang.Integer pk)
      throws javax.ejb.FinderException;

}
