/*
 * Generated by XDoclet - Do not edit!
 */
package com.csr.clients.ejb;

/**
 * CMP layer for ClientEntity.
 */
public abstract class ClientEntityCMP
   extends com.csr.clients.ejb.ClientEntityBean
   implements javax.ejb.EntityBean
{

   /**
    * Generated ejbPostCreate for corresponding ejbCreate method.
    *
    * @see #ejbCreate(com.csr.clients.ejb.ClientDTO clientDTO)
    */
   public void ejbPostCreate(com.csr.clients.ejb.ClientDTO clientDTO)
   {
   }

   public void ejbLoad() 
   {
   }

   public void ejbStore() 
   {
   }

   public void ejbActivate() 
   {
   }

   public void ejbPassivate() 
   {

      ClientDTO = null;
   }

   public void setEntityContext(javax.ejb.EntityContext ctx) 
   {
   }

   public void unsetEntityContext() 
   {
   }

   public void ejbRemove() throws javax.ejb.RemoveException
   {

   }

 /* Value Objects BEGIN */

   private com.csr.clients.dto.ClientDTO ClientDTO = null;

   public com.csr.clients.dto.ClientDTO getClientDTO()
   {
      ClientDTO = new com.csr.clients.dto.ClientDTO();
      try
         {
            ClientDTO.setClientID( getClientID() );
            ClientDTO.setClientName( getClientName() );
            ClientDTO.setClientNumber( getClientNumber() );
            ClientDTO.setCreditLimit( getCreditLimit() );
            ClientDTO.setBillable( getBillable() );

         }
         catch (Exception e)
         {
            throw new javax.ejb.EJBException(e);
         }

	  return ClientDTO;
   }

/* Value Objects END */

   public abstract java.lang.Integer getClientID() ;

   public abstract void setClientID( java.lang.Integer clientID ) ;

   public abstract java.lang.String getClientName() ;

   public abstract void setClientName( java.lang.String clientName ) ;

   public abstract java.lang.String getClientNumber() ;

   public abstract void setClientNumber( java.lang.String clientNumber ) ;

   public abstract java.lang.Double getCreditLimit() ;

   public abstract void setCreditLimit( java.lang.Double creditLimit ) ;

   public abstract java.lang.Boolean getBillable() ;

   public abstract void setBillable( java.lang.Boolean billable ) ;

}
