/*
 * Generated by XDoclet - Do not edit!
 */
package com.csr.common.ejb;

/**
 * Local home interface for UserEJB.
 */
public interface UserEJBLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/UserEJBLocal";
   public static final String JNDI_NAME="UserEJBLocal";

   public com.csr.common.ejb.UserEJBLocal create(java.lang.Integer id , java.lang.String firstName , java.lang.String lastName , java.lang.String address , java.lang.String city , java.lang.String state , java.lang.String zip , java.lang.String email)
      throws javax.ejb.CreateException;

   public java.util.Collection findAll()
      throws javax.ejb.FinderException;

   public com.csr.common.ejb.UserEJBLocal findByPrimaryKey(java.lang.Integer pk)
      throws javax.ejb.FinderException;

}
