/*
 * Generated by XDoclet - Do not edit!
 */
package com.csr.common.ejb;

/**
 * Local interface for UserEJB.
 */
public interface UserEJBLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * Id of this user.
    */
   public java.lang.Integer getId(  ) ;

   public java.lang.String getFirstName(  ) ;

   public java.lang.String getLastName(  ) ;

   public java.lang.String getAddress(  ) ;

   public java.lang.String getCity(  ) ;

   public java.lang.String getState(  ) ;

   public java.lang.String getZip(  ) ;

   public java.lang.String getEmail(  ) ;

   public com.csr.common.ejb.UserValue getUserValue(  ) ;

}
